### ISSUE TITLE
Error testing Menu in 1.3.0 with jest v22.0.4

### ISSUE THREAD

**Issue by ingesy** [jamesmfriedman/rmwc#167]
Hi

I have a problem doing snapshot testing on components including rmwc/Menu in our application. I've reduced the repro to this test.

```
import React from "react";
import renderer from "react-test-renderer";
import {MenuAnchor, Menu, MenuItem} from "rmwc/Menu/index";
import {Button} from "rmwc/Button/index";


describe("Repro", () => {

	test("repro", () => {
		const tree = renderer.create(
			<MenuAnchor>
				<Menu
					open={true}
					onClose={e => console.log("click")}
				>
					<MenuItem>Cookies</MenuItem>
					<MenuItem>Pizza</MenuItem>
					<MenuItem>Icecream</MenuItem>
				</Menu>

				<Button
					raised
					onClick={e => console.log("click")}
				>
					Open Menu
				</Button>
			</MenuAnchor>)
			.toJSON();
		expect(tree).toMatchSnapshot();
	});
});
```

```  Repro
    ✕ repro (20ms)

  ● Repro › repro

    TypeError: Cannot read property 'undefined' of undefined

       8 |
       9 | 	test('repro', () => {
    > 10 | 		const tree = renderer.create(
      11 | 			<MenuAnchor>
      12 | 				<Menu
      13 | 					open={true}

      at onUpdate (node_modules/rmwc/Menu/index.js:117:45)
      at _class.mdcComponentInit (node_modules/rmwc/Base/withMDC.js:147:11)
      at _class.componentDidMount (node_modules/rmwc/Base/withMDC.js:96:16)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4553:24)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5729:9)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1610:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1649:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1506:29)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5833:9)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6800:42)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6750:7)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6661:7)
      at scheduleWorkImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6515:11)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6472:12)
      at scheduleTopLevelUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6976:5)
      at Object.updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7014:7)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7637:18)
      at Object.<anonymous> (react-modules/test/repro.test.js:10:42)

  console.error node_modules/jest-runner/node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: Cannot read property 'undefined' of undefined]
        at reportException (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1649:16)
        at invokeGuardedCallback (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1506:29)
        at commitRoot (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5833:9)
        at performWorkOnRoot (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6800:42) TypeError: Cannot read property 'undefined' of undefined
        at onUpdate (/Users/inge/dev/src/tripletex/app/client/node_modules/rmwc/Menu/index.js:117:45)
        at _class.mdcComponentInit (/Users/inge/dev/src/tripletex/app/client/node_modules/rmwc/Base/withMDC.js:147:11)
        at _class.componentDidMount (/Users/inge/dev/src/tripletex/app/client/node_modules/rmwc/Base/withMDC.js:96:16)
        at commitLifeCycles (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4553:24)
        at commitAllLifeCycles (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5729:9)
        at HTMLUnknownElement.callCallback (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1610:14)
        at invokeEventListeners (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/Users/inge/dev/src/tripletex/app/client/node_modules/jest-runner/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1649:16)
        at invokeGuardedCallback (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1506:29)
        at commitRoot (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5833:9)
        at performWorkOnRoot (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6800:42)
        at performWork (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6750:7)
        at requestWork (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6661:7)
        at scheduleWorkImpl (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6515:11)
        at scheduleWork (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6472:12)
        at scheduleTopLevelUpdate (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6976:5)
        at Object.updateContainer (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7014:7)
        at Object.create (/Users/inge/dev/src/tripletex/app/client/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7637:18)
        at Object.<anonymous> (/Users/inge/dev/src/tripletex/app/client/react-modules/test/repro.test.js:10:42)
        at Object.asyncFn (/Users/inge/dev/src/tripletex/app/client/node_modules/jest/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
        at resolve (/Users/inge/dev/src/tripletex/app/client/node_modules/jest/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
        at new Promise (<anonymous>)
        at mapper (/Users/inge/dev/src/tripletex/app/client/node_modules/jest/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
        at promise.then (/Users/inge/dev/src/tripletex/app/client/node_modules/jest/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5530
    The above error occurred in the <withMDC(Menu)> component:
        in withMDC(Menu)
        in div (created by MenuAnchor)
        in MenuAnchor

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.```

**Comment by jamesmfriedman** [comment]
Without running your code, I already know that is telling you react-test-renderer is undefined. 

Check that you’re importing it correctly from the module. This is unrelated to rmwc. 

As far as rmwc goes, make sure you’ve included the test polyfill.

**Comment by jamesmfriedman** [comment]
Sorry, it’s telling you ‘renderer’ is undefined.

**Comment by ingesy** [comment]
This worked fine on a previous version of rmwc, our tests started to fail when we upgraded to 1.3.0.

I did some more debugging and it seems like both: 
_mdc.MDCMenuFoundation.Corner and ANCHOR_CORNER_MAP[nextProps.anchorCorner] are undefined. Do we need to run some other init code before running tests?

Here is our current setupTest.js
```
import 'babel-polyfill';
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import rmwcTestPolyfill from 'rmwc/Base/testPolyfill';
Enzyme.configure({ adapter: new Adapter() });

//import and run this to fix the the MDC errors
rmwcTestPolyfill();

//these will fail tests if not mocked.
jest.mock("@material/ripple/dist/mdc.ripple");
jest.mock("@material/menu/dist/mdc.menu");
```

**Comment by ingesy** [comment]
I resolved this using enzyme to render instead of react-test-renderer.

**Comment by jamesmfriedman** [comment]
Oh that makes sense @ingesy. Glad you got it resolved!
