### ISSUE TITLE
Breaks create-react-app tests

### ISSUE THREAD

**Issue by schliflo** [jamesmfriedman/rmwc#223]
*I just wanted to leave this here for documentation purposes*
### What RMWC Version are you using?

1.6.1

### What build system are you using?

Create React App (probably not specific for that)

### What are the steps to reproduce the bug?

`npx create-react-app tmp`
`yarn add rmwc`
use Button component in App.js:
```jsx
import React, { Component } from 'react';
import { Button } from 'rmwc/Button';

class App extends Component {
  render() {
    return (
        <Button>Hello World</Button>
    );
  }
}

export default App;
```
`yarn test`

### What is the expected behavior?

`yarn test` should exit without errors

### What is the actual behavior?

`yarn test` showing this error:
```
 FAIL  src/App.test.js
  ● renders without crashing

    TypeError: Cannot use 'in' operator to search for 'mdcRippleIsUnbounded' in undefined

      at Ripple.initialSyncWithDOM (node_modules/@material/ripple/dist/mdc.ripple.js:810:47)
      at Ripple.initFoundation (node_modules/rmwc/Base/MDCFoundation.js:196:14)
      at Ripple.componentDidMount (node_modules/rmwc/Base/MDCFoundation.js:156:14)
      at Ripple.componentDidMount (node_modules/rmwc/Ripple/index.js:57:110)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:9784:26)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:11455:9)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:100:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:138:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:11594:9)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:12502:36)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:12452:11)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:12370:9)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:12347:5)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:12247:7)
      at scheduleWorkImpl (node_modules/react-dom/cjs/react-dom.development.js:12122:13)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:12082:12)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:12710:5)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:12738:12)
      at Object.updateContainer (node_modules/react-dom/cjs/react-dom.development.js:12765:14)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:16069:15)
      at node_modules/react-dom/cjs/react-dom.development.js:16488:14
      at Object.unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:12557:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:16484:17)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:16543:12)
      at Object.<anonymous>.it (src/App.test.js:7:22)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)

  ✕ renders without crashing (24ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.014s
```

### How I solved it
Add polyfills to the tests like so (App.test.js):
```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import rmwcTestPolyfill from 'rmwc/Base/testPolyfill';

// run the rmwc polyfills
rmwcTestPolyfill();

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
```

**Comment by jamesmfriedman** [comment]
@schliflo this is documented in the getting started guide. Do I need to call it out better?

**Comment by schliflo** [comment]
@jamesmfriedman Oh - seems like I overlooked that. I was searching for the error and didn't find any relevant information, so i figured it'd be good to leave this issue here.
It's most likely fine as it is.
