### ISSUE TITLE
storyshots break on things with ripples

### ISSUE THREAD

**Issue by konsumer** [jamesmfriedman/rmwc#230]
## RMWC or MDC?

It's MDC (see [material-components-web#2023](https://github.com/material-components/material-components-web/issues/2023)), but also RMWC, as it uses the`@material/ripple/dist/mdc.ripple` directly, now.

### What RMWC Version are you using?

1.6.3

### What browser(s) and React Version is this bug affecting?

React 16.3.2
Jest 22.4.4

### What build system are you using?

Only jest (from create-react-app), storybook, and storyshots

### What are the steps to reproduce the bug?

See [this repo](https://github.com/konsumer/rmwc-storyshots)

* `npm i` - to install dependencies
* `npm test` - to run storyshots
* `npm start` - to see the storybook

### What is the expected behavior?

I should be able to run storyshots on stories that include components that have `Ripple`. I'm happy to mock out anything that will prevent the errors, but it hasn't worked with any of these:

```js
jest.mock('@material/ripple')
jest.mock('rmwc/Base/MDCFoundation.js')
jest.mock('rmwc/Ripple/index.js')
jest.mock("@material/ripple/dist/mdc.ripple")
```

It also doesn't work with the suggested solution of `element-dataset`.

### What is the actual behavior?

I get this error:

```
    TypeError: Cannot use 'in' operator to search for 'mdcRippleIsUnbounded' in undefined

      at Ripple.initialSyncWithDOM (node_modules/@material/ripple/dist/mdc.ripple.js:810:47)
      at Ripple.initFoundation (node_modules/rmwc/Base/MDCFoundation.js:196:14)
      at Ripple.componentDidMount (node_modules/rmwc/Base/MDCFoundation.js:156:14)
      at Ripple.componentDidMount (node_modules/rmwc/Ripple/index.js:57:110)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5347:26)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7018:9)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:906:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:944:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:993:29)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7157:9)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8065:36)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8015:11)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7933:9)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7910:5)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7810:7)
      at scheduleWorkImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7685:13)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7645:12)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8273:5)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8301:12)
      at Object.updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8328:14)
      at create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9009:18)
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/react/renderTree.js:24:14)
      at node_modules/@storybook/addon-storyshots/dist/test-bodies.js:21:18
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:125:20)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
```

**Comment by konsumer** [comment]
Strangely, I originally discovered the issue making [this project](https://github.com/konsumer/rmwc-fabmenu), and it appears to work fine.

I've only got this in there:

```js
jest.mock('@material/ripple/dist/mdc.ripple')
```

Which I tried in the other demo project, and it didn't work, but it seems fine, in this project.

**Comment by jamesmfriedman** [comment]
You need to include the test polyfill that is listed in the getting started guide of the docs. Storybook has a different code path than your standard tests so you’ll have to include it in your storybook config file.

**Comment by konsumer** [comment]
This is great to know, but now I'm confused why it works with out that.

**Comment by jamesmfriedman** [comment]
anything else on this @konsumer

**Comment by konsumer** [comment]
I'm really not sure why it works without the polyfill, but feel free to close. Thanks for the explanation.
