### ISSUE TITLE
Importing snackbar generates an error.

### ISSUE THREAD

**Issue by G-T-P** [jamesmfriedman/rmwc#381]
I have tried to reproduce the error in the sandbox but I couldn't. However I was able to fix it.

Error:
```
repo\node_modules\@rmwc\snackbar\node_modules\@material\animation\index.js:149
export {transformStyleProperties, getCorrectEventName, getCorrectPropertyName};
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (proj\repo\node_modules\@rmwc\snackbar\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
Just a simple `import { Snackbar } from '@rmwc/snackbar'` triggers the error, even if I do not use the component.

Looking into the transpiled code the issue was corrected by changing: `snackbar>index.js` on line 18 from:

`var _animation = require('@material/animation');`

to: 

`var _animation = require('@material/animation/dist/mdc.animation');`

Which makes me think that it is a language transpiling issue.

**Comment by jamesmfriedman** [comment]
Thank you! Definitely an oversight. Will get this patched tomorrow morning.

**Comment by javecruzCapgemini** [comment]
Any news on this? Still have this problem.

**Comment by javecruz** [comment]
Any news on this? We still have this problem.

**Comment by jamesmfriedman** [comment]
Sorry, still in full holiday family mode, but got a patch release out for you. 4.0.3

**Comment by javecruzCapgemini** [comment]
Thank you very much. Sorry for disturbing you relax time !
Enjoy.
